version: '3.9'
services:

  api01: &api
    image: maxwellmonteiro/crinha:latest
    hostname: api01  
    command: ./rinha
    environment:
      PORT: 8080
      DB_CONNECTION_STR: "user=rinha password=rinha dbname=rinha host=db port=5432"
    depends_on: 
      - db
    expose:
      - 8080
    # network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '10MB'

  api02:
    <<: *api
    hostname: api02       

  db:
    image: postgres:15
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf    
    hostname: db
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_DB=rinha
    expose:
      - 5432
    ports:
      - "5433:5432"
    # network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '1.30'
          memory: '440MB' 
         
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02  
    ports:
      - "9999:9999"
    # network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '90MB'
