version: "3"
# 1.5 550MB
# 0.5 200
# 0.4 150
# 0.4 150
# 0.2 50
services:
  database:
    image: postgres:16-alpine
    command: postgres -c 'max_connections=20'
    ports:
      - "5432:5432"
    env_file: ../../.env
    restart: no
    volumes:
      - ../sql/script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 20

  api01: &api
    image: yanpgabriel/quarkus-rinha-2024-q1:latest
    env_file: ../../.env
    ports:
      - "8081:8080"
    networks:
      - default
    depends_on:
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  api02:
    # Essa sintaxe reusa o que foi declarado em 'api01'.
    <<: *api
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
networks:
  default:
    driver: bridge