version: "3"

services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC receiver
      #- "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      #- "14268:14268" # Receive legacy OpenTracing traces, optional
      #- "14250:14250" # Receive from external otel-collector, optional
    env_file: ../../.env
    environment:
      - COLLECTOR_OTLP_ENABLED=true